# Auto-generated expanded merchant category dictionary
MERCHANT_RULES = {
    "netflix": "Entertainment",
    "hotstar": "Entertainment",
    "disney": "Entertainment",
    "disney+": "Entertainment",
    "prime video": "Entertainment",
    "amazon prime": "Entertainment",
    "spotify": "Entertainment",
    "youtube premium": "Entertainment",
    "youtube music": "Entertainment",
    "gaana": "Entertainment",
    "wynk": "Entertainment",
    "jiosaavn": "Entertainment",
    "bookmyshow": "Entertainment",
    "pvr": "Entertainment",
    "inox": "Entertainment",
    "cinepolis": "Entertainment",
    "sonyliv": "Entertainment",
    "zee5": "Entertainment",
    "voot": "Entertainment",
    "altbalaji": "Entertainment",
    "mxplayer": "Entertainment",
    "steam": "Entertainment",
    "playstation": "Entertainment",
    "xbox": "Entertainment",
    "nintendo": "Entertainment",
    "epic games": "Entertainment",
    "gaming zone": "Entertainment",
    "arcade": "Entertainment",
    "bowling": "Entertainment",
    "amusement park": "Entertainment",
    "wonderla": "Entertainment",
    "imagica": "Entertainment",
    "essel world": "Entertainment",
    "waterpark": "Entertainment",
    "carnival cinemas": "Entertainment",
    "audible": "Entertainment",
    "kindle unlimited": "Entertainment",
    "storytel": "Entertainment",
    "tinder": "Entertainment",
    "bumble": "Entertainment",
    "hinge": "Entertainment",
    "amazon.in": "Shopping",
    "amazon pay": "Shopping",
    "flipkart": "Shopping",
    "myntra": "Shopping",
    "ajio": "Shopping",
    "meesho": "Shopping",
    "nykaa": "Shopping",
    "nykaa fashion": "Shopping",
    "reliance digital": "Shopping",
    "reliance trends": "Shopping",
    "reliance retail": "Shopping",
    "croma": "Shopping",
    "lenskart": "Shopping",
    "titan": "Shopping",
    "tanishq": "Shopping",
    "decathlon": "Shopping",
    "urban company": "Shopping",
    "ikea": "Shopping",
    "pepperfry": "Shopping",
    "firstcry": "Shopping",
    "snapdeal": "Shopping",
    "shopclues": "Shopping",
    "tatacliq": "Shopping",
    "westside": "Shopping",
    "lifestyle": "Shopping",
    "pantaloons": "Shopping",
    "max fashion": "Shopping",
    "h&m": "Shopping",
    "zara": "Shopping",
    "levis": "Shopping",
    "puma": "Shopping",
    "nike": "Shopping",
    "adidas": "Shopping",
    "boat lifestyle": "Shopping",
    "noise": "Shopping",
    "vijay sales": "Shopping",
    "big bazaar": "Shopping",
    "central mall": "Shopping",
    "shoppers stop": "Shopping",
    "chroma": "Shopping",
    "under armour": "Shopping",
    "bata": "Shopping",
    "woodland": "Shopping",
    "van heusen": "Shopping",
    "allen solly": "Shopping",
    "peter england": "Shopping",
    "fabindia": "Shopping",
    "biba": "Shopping",
    "w for women": "Shopping",
    "global desi": "Shopping",
    "sephora": "Shopping",
    "purplle": "Shopping",
    "hopscotch": "Shopping",
    "chumbak": "Shopping",
    "caratlane": "Shopping",
    "bluestone": "Shopping",
    "gadgets 360": "Shopping",
    "poorvika": "Shopping",
    "sangeetha mobiles": "Shopping",
    "mi store": "Shopping",
    "samsung store": "Shopping",
    "apple store": "Shopping",
    "oneplus": "Shopping",
    "jbl": "Shopping",
    "boat store": "Shopping",
    "blinkit": "Groceries",
    "zepto": "Groceries",
    "bigbasket": "Groceries",
    "dmart": "Groceries",
    "d mart": "Groceries",
    "jiomart": "Groceries",
    "instamart": "Groceries",
    "swiggy instamart": "Groceries",
    "grofers": "Groceries",
    "spencers": "Groceries",
    "more supermarket": "Groceries",
    "more retail": "Groceries",
    "nature basket": "Groceries",
    "milk basket": "Groceries",
    "country delight": "Groceries",
    "kirana": "Groceries",
    "vegetable": "Groceries",
    "sabzi": "Groceries",
    "grocery": "Groceries",
    "supermarket": "Groceries",
    "ration": "Groceries",
    "star bazaar": "Groceries",
    "easyday": "Groceries",
    "nilgiris": "Groceries",
    "heritage fresh": "Groceries",
    "vishal mega mart": "Groceries",
    "24seven": "Groceries",
    "swiggy": "Food",
    "zomato": "Food",
    "dominos": "Food",
    "pizza hut": "Food",
    "mcdonald": "Food",
    "kfc": "Food",
    "burger king": "Food",
    "starbucks": "Food",
    "costa coffee": "Food",
    "cafe coffee day": "Food",
    "ccd": "Food",
    "chai point": "Food",
    "chaayos": "Food",
    "third wave coffee": "Food",
    "blue tokai": "Food",
    "cafe": "Food",
    "restaurant": "Food",
    "dhaba": "Food",
    "eatsure": "Food",
    "faasos": "Food",
    "behrouz": "Food",
    "oven story": "Food",
    "lunch box": "Food",
    "biryani": "Food",
    "subway": "Food",
    "haldiram": "Food",
    "bikanervala": "Food",
    "bakery": "Food",
    "sweets": "Food",
    "theobroma": "Food",
    "monginis": "Food",
    "baskin robbins": "Food",
    "naturals ice cream": "Food",
    "kwality walls": "Food",
    "amul": "Food",
    "wow momo": "Food",
    "box8": "Food",
    "freshmenu": "Food",
    "eatfit": "Food",
    "rebel foods": "Food",
    "barbeque nation": "Food",
    "absolute barbecues": "Food",
    "social": "Food",
    "hard rock cafe": "Food",
    "pind balluchi": "Food",
    "sagar ratna": "Food",
    "uber": "Travel",
    "ola cabs": "Travel",
    "ola": "Travel",
    "rapido": "Travel",
    "meru cabs": "Travel",
    "irctc": "Travel",
    "indian railway": "Travel",
    "indigo": "Travel",
    "spicejet": "Travel",
    "vistara": "Travel",
    "air india": "Travel",
    "akasa air": "Travel",
    "goair": "Travel",
    "makemytrip": "Travel",
    "goibibo": "Travel",
    "redbus": "Travel",
    "cleartrip": "Travel",
    "yatra": "Travel",
    "agoda": "Travel",
    "booking.com": "Travel",
    "trivago": "Travel",
    "oyo": "Travel",
    "airbnb": "Travel",
    "treebo": "Travel",
    "fabhotels": "Travel",
    "taj hotels": "Travel",
    "marriott": "Travel",
    "hilton": "Travel",
    "hotel": "Travel",
    "resort": "Travel",
    "petrol": "Travel",
    "diesel": "Travel",
    "fuel station": "Travel",
    "hpcl": "Travel",
    "iocl": "Travel",
    "bpcl": "Travel",
    "shell petrol": "Travel",
    "fastag": "Travel",
    "toll plaza": "Travel",
    "parking": "Travel",
    "metro card": "Travel",
    "namma metro": "Travel",
    "dmrc": "Travel",
    "mmrda": "Travel",
    "bmtc": "Travel",
    "best bus": "Travel",
    "state transport": "Travel",
    "msrtc": "Travel",
    "car rental": "Travel",
    "zoomcar": "Travel",
    "revv": "Travel",
    "drivezy": "Travel",
    "airtel": "Bills",
    "jio recharge": "Bills",
    "jio fiber": "Bills",
    "vi prepaid": "Bills",
    "vodafone idea": "Bills",
    "bsnl": "Bills",
    "electricity bill": "Bills",
    "mahavitaran": "Bills",
    "mahadiscom": "Bills",
    "bses": "Bills",
    "tata power": "Bills",
    "adani electricity": "Bills",
    "torrent power": "Bills",
    "gas bill": "Bills",
    "indane gas": "Bills",
    "hp gas": "Bills",
    "bharat gas": "Bills",
    "broadband bill": "Bills",
    "act fibernet": "Bills",
    "hathway": "Bills",
    "excitel": "Bills",
    "dth recharge": "Bills",
    "tata sky": "Bills",
    "dish tv": "Bills",
    "d2h": "Bills",
    "sun direct": "Bills",
    "airtel digital tv": "Bills",
    "insurance premium": "Bills",
    "lic premium": "Bills",
    "hdfc life": "Bills",
    "icici prudential": "Bills",
    "sbi life": "Bills",
    "max life": "Bills",
    "star health": "Bills",
    "water bill": "Bills",
    "maintenance charge": "Bills",
    "society maintenance": "Bills",
    "property tax": "Bills",
    "municipal tax": "Bills",
    "pharmacy": "Healthcare",
    "apollo pharmacy": "Healthcare",
    "apollo hospital": "Healthcare",
    "fortis": "Healthcare",
    "max healthcare": "Healthcare",
    "manipal hospital": "Healthcare",
    "hospital": "Healthcare",
    "clinic": "Healthcare",
    "medplus": "Healthcare",
    "1mg": "Healthcare",
    "tata 1mg": "Healthcare",
    "pharmeasy": "Healthcare",
    "netmeds": "Healthcare",
    "diagnostic centre": "Healthcare",
    "pathology lab": "Healthcare",
    "dr lal pathlabs": "Healthcare",
    "srl diagnostics": "Healthcare",
    "metropolis": "Healthcare",
    "medical store": "Healthcare",
    "dentist": "Healthcare",
    "optical": "Healthcare",
    "practo": "Healthcare",
    "physiotherapy": "Healthcare",
    "udemy": "Education",
    "coursera": "Education",
    "byjus": "Education",
    "unacademy": "Education",
    "vedantu": "Education",
    "physics wallah": "Education",
    "toppr": "Education",
    "whitehat jr": "Education",
    "college fee": "Education",
    "school fee": "Education",
    "tuition fee": "Education",
    "skillshare": "Education",
    "linkedin learning": "Education",
    "great learning": "Education",
    "upgrad": "Education",
    "simplilearn": "Education",
    "khan academy": "Education",
    "duolingo": "Education",
    "rem chrg": "Bank Charges",
    "sms alert fee": "Bank Charges",
    "annual fee": "Bank Charges",
    "gst charge": "Bank Charges",
    "penalty charge": "Bank Charges",
    "minimum balance charge": "Bank Charges",
    "amc charge": "Bank Charges",
    "processing fee": "Bank Charges",
    "late fee": "Bank Charges",
    "cheque bounce": "Bank Charges",
    "overdraft charge": "Bank Charges",
    "atm charge": "Bank Charges",
    "card replacement fee": "Bank Charges",
    "atm withdrawal": "Cash Withdrawal",
    "cash withdrawal": "Cash Withdrawal",
    "cash deposit": "Cash Withdrawal",
    "cdm deposit": "Cash Withdrawal",
    "zerodha": "Investment",
    "groww": "Investment",
    "upstox": "Investment",
    "mutual fund": "Investment",
    "sip": "Investment",
    "mudrex": "Investment",
    "coindcx": "Investment",
    "wazirx": "Investment",
    "binance": "Investment",
    "coinbase": "Investment",
    "paytm money": "Investment",
    "kuvera": "Investment",
    "angel one": "Investment",
    "icici direct": "Investment",
    "hdfc securities": "Investment",
    "nps contribution": "Investment",
    "ppf deposit": "Investment",
    "fixed deposit": "Investment",
    "recurring deposit": "Investment",
    "sovereign gold bond": "Investment",
    "digital gold": "Investment",
    "google one": "Subscriptions",
    "icloud storage": "Subscriptions",
    "chatgpt": "Subscriptions",
    "openai": "Subscriptions",
    "claude ai": "Subscriptions",
    "canva": "Subscriptions",
    "adobe": "Subscriptions",
    "microsoft 365": "Subscriptions",
    "notion": "Subscriptions",
    "dropbox": "Subscriptions",
    "github": "Subscriptions",
    "figma": "Subscriptions",
    "zoom subscription": "Subscriptions",
    "salon": "Personal Care",
    "spa": "Personal Care",
    "gym membership": "Personal Care",
    "fitness first": "Personal Care",
    "cult.fit": "Personal Care",
    "cultfit": "Personal Care",
    "gold gym": "Personal Care",
    "anytime fitness": "Personal Care",
    "naturals salon": "Personal Care",
    "lakme salon": "Personal Care",
    "vlcc": "Personal Care",
    "urban clap": "Personal Care",
    "house rent": "Rent",
    "rent payment": "Rent",
    "nobroker": "Rent",
    "housing.com": "Rent",
    "magicbricks": "Rent",
    "99acres": "Rent",
    "brokerage": "Bank Charges",
    "demat charge": "Bank Charges",
    "pampers": "Kids & Baby",
    "huggies": "Kids & Baby",
    "mothercare": "Kids & Baby",
    "hopscotch baby": "Kids & Baby",
    "toys r us": "Kids & Baby",
    "fisher price": "Kids & Baby",
    "chicco": "Kids & Baby",
    "himalaya baby": "Kids & Baby",
    "johnson baby": "Kids & Baby",
    "daycare": "Kids & Baby",
    "creche": "Kids & Baby",
    "playschool": "Kids & Baby",
    "heads up for tails": "Pets",
    "petsy": "Pets",
    "supertails": "Pets",
    "pet clinic": "Pets",
    "veterinary": "Pets",
    "pedigree": "Pets",
    "whiskas": "Pets",
    "pet grooming": "Pets",
    "dogspot": "Pets",
    "donation": "Charity",
    "ngo": "Charity",
    "give india": "Charity",
    "temple donation": "Charity",
    "charity": "Charity",
    "crowdfunding": "Charity",
    "ketto": "Charity",
    "milaap": "Charity",
    "office supplies": "Office",
    "staples": "Office",
    "cartridge world": "Office",
    "coworking space": "Office",
    "wework": "Office",
    "regus": "Office",
    "courier": "Office",
    "bluedart": "Office",
    "delhivery": "Office",
    "dtdc": "Office",
    "fedex": "Office",
    "india post": "Office",
    "speed post": "Office",
    "hardware store": "Home Improvement",
    "paint shop": "Home Improvement",
    "asian paints": "Home Improvement",
    "berger paints": "Home Improvement",
    "plumber": "Home Improvement",
    "electrician": "Home Improvement",
    "carpenter": "Home Improvement",
    "urban ladder": "Home Improvement",
    "godrej interio": "Home Improvement",
    "nilkamal": "Home Improvement",
    "havells": "Home Improvement",
    "bajaj electricals": "Home Improvement",
    "ebay": "Shopping",
    "aliexpress": "Shopping",
    "club factory": "Shopping",
    "koovs": "Shopping",
    "limeroad": "Shopping",
    "voonik": "Shopping",
    "jabong": "Shopping",
    "paytm mall": "Shopping",
    "shopsy": "Shopping",
    "meesho supplier": "Shopping",
    "purplle beauty": "Shopping",
    "mamaearth": "Shopping",
    "sugar cosmetics": "Shopping",
    "plum goodness": "Shopping",
    "dunkin donuts": "Food",
    "krispy kreme": "Food",
    "wendys": "Food",
    "taco bell": "Food",
    "pizza express": "Food",
    "la pinoz": "Food",
    "smokehouse deli": "Food",
    "chai wala": "Food",
    "irani cafe": "Food",
    "juice shop": "Food",
    "sharbat": "Food",
    "roadside dhaba": "Food",
    "food truck": "Food",
    "canteen": "Food",
    "mess bill": "Food",
    "flight ticket": "Travel",
    "train ticket": "Travel",
    "bus ticket": "Travel",
    "self drive car": "Travel",
    "myles": "Travel",
    "bounce scooter": "Travel",
    "yulu": "Travel",
    "vogo": "Travel",
    "auto rickshaw": "Travel",
    "cab booking": "Travel",
    "airport parking": "Travel",
    "lounge access": "Travel",
    "visa fee": "Travel",
    "passport fee": "Travel",
    "forex card": "Travel",
    "postpaid bill": "Bills",
    "prepaid recharge": "Bills",
    "landline bill": "Bills",
    "sun tv": "Bills",
    "videocon d2h": "Bills",
    "life insurance premium": "Bills",
    "term insurance": "Bills",
    "vehicle insurance": "Bills",
    "car insurance": "Bills",
    "bike insurance": "Bills",
    "health insurance premium": "Bills",
    "columbia asia": "Healthcare",
    "narayana health": "Healthcare",
    "aster hospital": "Healthcare",
    "care hospital": "Healthcare",
    "cult diagnostics": "Healthcare",
    "thyrocare": "Healthcare",
    "physio clinic": "Healthcare",
    "ayurveda clinic": "Healthcare",
    "homeopathy": "Healthcare",
    "eye hospital": "Healthcare",
    "chegg": "Education",
    "brilliant.org": "Education",
    "codecademy": "Education",
    "pluralsight": "Education",
    "edx": "Education",
    "aakash institute": "Education",
    "allen career": "Education",
    "fiitjee": "Education",
    "resonance": "Education",
    "national institute": "Education",
    "exam fee": "Education",
    "certification fee": "Education",
    "apple music": "Entertainment",
    "resso": "Entertainment",
    "hungama music": "Entertainment",
    "tiktok": "Entertainment",
    "instagram subscription": "Entertainment",
    "twitch": "Entertainment",
    "discord nitro": "Entertainment",
    "board game cafe": "Entertainment",
    "escape room": "Entertainment",
    "trampoline park": "Entertainment",
    "go karting": "Entertainment",
    "laser tag": "Entertainment",
    "snooker club": "Entertainment",
}